# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aunderwo-gcal4ruby}
  s.version = "0.5.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Reich", "Anthony Underwood"]
  s.date = %q{2010-10-01}
  s.email = ["mike@seabourneconsulting.com", "email2ants@gmail.com"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGELOG",
     "README",
     "lib/gcal4ruby.rb",
     "lib/gcal4ruby/calendar.rb",
     "lib/gcal4ruby/event.rb",
     "lib/gcal4ruby/recurrence.rb",
     "lib/gcal4ruby/service.rb"
  ]
  s.homepage = %q{http://github.com/aunderwo/GCal4Ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A full featured wrapper for interacting with the Google Calendar API}
  s.test_files = [
    "test/unit.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

